# docker-compose.backend.yml
version: '3.8'

services:
  # Base de datos MongoDB
  database:
    image: mongo:7.0.2
    container_name: database_amas
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - /disk4/amas/database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=amasMaster
      - MONGO_INITDB_ROOT_PASSWORD=*AmAsMaStErFiRst1
    command: --auth
    networks:
      - web

  # Backend del sistema AMAS
  amasbackend:
    image: amasbackend
    container_name: amasbackend
    restart: on-failure:10
    build: .
    command: node ./dist/index.js
    expose:
      - "3500"
    environment:
      - VIRTUAL_HOST=amass.com.co
      - LETSENCRYPT_HOST=amass.com.co
      - LETSENCRYPT_EMAIL=soporteti@amass.com.co
      - VIRTUAL_PORT=3500
      - VIRTUAL_PATH=/api
    volumes:
      - /disk4/amas/imagesProducts:/home/imagesProducts
      - /disk4/amas/imagesMarks:/home/imagesMarks
      - /disk4/amas/imagesCategories:/home/imagesCategories
      - /disk4/amas/supportsPayments:/home/supportsPayments
      - /disk4/amas/pdfQuotes:/home/pdfQuotes
      - /disk4/amas/pdfOrder:/home/pdfOrder
      - /disk4/amas/files:/home/files
      - /disk4/amas/temp:/home/temp
      - /disk4/amas/scripts/pythonScripts:/home/scripts/pythonScripts
    depends_on:
      - database
    networks:
      - web

networks:
  web:
    external: true

# docker-compose -f docker-compose.backend.yml up -d