# docker-compose.frontends.yml
version: '3.8'

services:
  # Frontend del sistema AMAS (no-SSR)
  donmariofrontend:
    image: donmariofrontend
    container_name: donmariofrontend
    build: /disk1/donmario/DonMario
    restart: always
    expose:
      - "8085"
    environment:
      - VIRTUAL_HOST=amas.com.co
      - LETSENCRYPT_HOST=amas.com.co
      - LETSENCRYPT_EMAIL=soporteti@amass.com.co
      - VIRTUAL_PORT=8085
      - VIRTUAL_PATH=/
    networks:
      - web
      
networks:
  web:
    external: true

# docker-compose -f docker-compose.frontend.yml up -d