# docker-compose.frontendSsr.yml
version: '3.8'

services:
  # Frontend SSR del sistema AMAS
  amasfrontendssr:
    image: amas-frontend-ssr
    container_name: amasfrontendssr
    build: /disk1/amas/amasFrontendSsr
    restart: always
    expose:
      - "4000"
    environment:
      - VIRTUAL_HOST=ferreteria.amass.com.co
      - LETSENCRYPT_HOST=ferreteria.amass.com.co
      - LETSENCRYPT_EMAIL=soporteti@amass.com.co
      - VIRTUAL_PORT=4000
      - VIRTUAL_PATH=/
      - API_URL=http://amasbackend:3500 # Se comunica con el backend por la red 'web'
    networks:
      - web

networks:
  web:
    external: true

# docker-compose -f docker-compose.frontendSsr.yml up -d